name: windows 10 ltsc collabvm

on: [push, workflow_dispatch]

defaults:
  run:
    shell: bash

jobs:
  collabvm_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing node.js and npm...
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Installing and configuring CollabVM + QEMU...
        run: |
          sudo apt update
          sudo apt install qemu-kvm qemu-system-x86 libossp-uuid16 libvncserver1 libvncclient1 libodb-sqlite-2.4
          npm install -g localtunnel
          git clone https://github.com/legoskid/compiled-collab-vm-server-linux
          ls && cd compiled-collab-vm-server-linux/cvm/final && chmod +x collab-vm-server && sudo ./collab-vm-server 6004 &
          lt --port 6004 | tee lt.txt &
          cat lt.txt &
          curl -k https://loca.lt/mytunnelpassword &
          curl -k -O https://dl.bobpony.com/windows/10/en-us_windows_10_enterprise_ltsc_2021_x64_dvd_d289cf96.iso
          qemu-img create -f qcow2 win10.qcow2 20G
          echo Please use the QEMU command, qemu-system-x86_64 -accel kvm --cpu host -m 12G -smp 4 -hda win10.qcow2 -cdrom en-us_windows_10_enterprise_ltsc_2021_x64_dvd_d289cf96.iso -boot d -display vnc=127.0.0.1:0,password=off -qmp tcp:127.0.0.1:4444,server,wait=off -vga qxl.
          sleep infinity
