name: Ubuntu
on: 
  workflow_dispatch:
jobs:
  build:
    name: Ubuntu
    runs-on: ubuntu-latest
    
    steps:                 
    - name: Install Sshx
      run: |
          curl -sSf https://sshx.io/get | sh          
    - name: Start sshx
      run: |
         sshx
         
    - name: Ubuntu System running...
